### ISSUE TITLE
PB Mainpage 관련 기능  

### ISSUE THREAD

**Issue by younghyun-na** [shs-g1/server#4]
## 📝 Description
PB mainpage에서 사용되는 기능입니다.

## ✅ Todo
- [x] 캘린더에 일정 추가하는 기능
- [x] main page에서 캘린더와 고객 리스트 확인하는 기능
- [x] 수익률 계산하는 기능
