### ISSUE TITLE
고객 자산 관리 현황 관련 기능

### ISSUE THREAD

**Issue by younghyun-na** [shs-g1/server#5]
## 📝 Description
고객 자산 관리 현황에 관련된 기능입니다.

## ✅ Todo
- [x] 고객 기본 정보 
- [x] 포트폴리오 기능
- [x] 수익률 그래프 기능
- [x] 계좌 현황 기능
- [x] 잔고 체결 내역 관리 기능
