### ISSUE TITLE
pb page 구현

### ISSUE THREAD

**Issue by BoyoungH** [shs-g1/server#6]
## 📝 Description
PB 이력을 보여주는 페이지입니다.

## ✅ Todo
- [ ] erd db수정
- [ ] db entity 수정 -> 포트폴리오 테이블 만들어서 거래내역 테이블과 연결
- [ ] 지금까지 한 기능들 dev로 pr 날리기
- [ ] pb 페이지 crud 작업
